---
settings:
  name: BlueXP replication
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: it-it,us-en,de-de,es-es,fr-fr,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documenti sulla replica BlueXP
    url: "/index.html"
  - title: Note di rilascio
    entries:
    - title: Novità
      url: "/whats-new.html"
  - title: Inizia subito
    entries:
    - title: Scopri di più sulla replica BlueXP
      url: "/concept-replication.html"
    - title: Configurare la replica dei dati
      url: "/task-replicating-data.html"
  - title: Gestire la replica dei dati
    url: "/task-managing-replication.html"
  - title: Scopri di più
    entries:
    - title: Scopri le policy di replica
      url: "/concept-replication-policies.html"
    - title: Scopri le politiche di backup
      url: "/concept-backup-policies.html"
  - title: Conoscenza e supporto
    entries:
    - title: Registrati per ricevere assistenza
      url: "/task-support-registration.html"
    - title: Richiedi assistenza
      url: "/task-get-help.html"
  - title: Note legali
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
